'use client';
import {useState} from 'react';
import {ArrowRight,ArrowUpRight,Activity,Code2,Download,FileText,GraduationCap,Info,Layers,Link2,LoaderCircle,Play,RefreshCw,ShieldCheck,Workflow} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {departments,mappings,type Department} from '@/lib/demo';
import {Badge,api,download} from './workspace';
import {deptInfo} from './apply';
import Guide from './guide';
export default function Views({ctx:c}:any){
 const [search,setSearch]=useState(''),[dept,setDept]=useState<Department>('education'),[response,setResponse]=useState<any>(null),[status,setStatus]=useState('');
 const logs=c.workspace.audit,requests=logs.filter((l:any)=>l.action==='Department request'),successes=requests.filter((l:any)=>l.outcome==='success').length;
 const apps=c.workspace.applications.filter((a:any)=>(a.id+' '+a.name+' '+a.citizen_id).toLowerCase().includes(search.toLowerCase()));
 async function send(){c.setBusy(true);setResponse(null);try{const d=await api(`departments/${dept}/${c.app.citizen_id}?applicationId=${encodeURIComponent(c.app.id)}${c.outage?'&simulate=unavailable':''}`);setResponse(d);setStatus('200 OK');c.setRecords((s:any)=>({...s,[dept]:d}))}catch(e:any){setResponse({error:e.message});setStatus(`${e.status||503} Error`)}finally{c.setBusy(false);await c.refresh()}}
 if(c.view==='guide')return <Guide/>;
 if(c.view==='applications')return <div className="panel"><div className="panel-head"><h2>Application history <span className="muted">({c.workspace.applications.length})</span></h2><div className="field"><input aria-label="Search applications" placeholder="Search name or reference" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{apps.length?<Table className="data-table"><TableHeader><TableRow><TableHead>Applicant</TableHead><TableHead>Reference</TableHead><TableHead>Status</TableHead><TableHead>Created</TableHead><TableHead>Action</TableHead></TableRow></TableHeader><TableBody>{apps.map((a:any)=><TableRow key={a.id}><TableCell><strong>{a.name}</strong><div className="subtext">{a.citizen_id}</div></TableCell><TableCell title={a.id}>{a.id.slice(0,11)}…</TableCell><TableCell><Badge status={a.status}/></TableCell><TableCell>{new Date(a.created_at).toLocaleDateString('en-IN')}</TableCell><TableCell><button className="btn small" onClick={()=>c.openApp(a)} disabled={c.busy}>Open<ArrowUpRight size={14}/></button></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><FileText size={30}/><h3>{search?'No matching applications':'Your applications will appear here'}</h3><p>Complete the consent step to save your first application.</p><button className="btn primary" style={{marginTop:18}} onClick={c.reset}>Start an application</button></div>}</div>;
 if(c.view==='dashboard')return <><div className="stats">{[['Saved applications',c.workspace.applications.length,'Latest 100 applications'],['Sample API requests',requests.length,'Latest 200 audit events'],['Successful requests',requests.length?Math.round(successes/requests.length*100)+'%':'—','Based on recorded requests'],['Requests needing attention',requests.length-successes,'Failed sample department calls']].map(([title,n,desc])=><div className="panel stat" key={String(title)}><span className="muted" style={{fontSize:14}}>{title}</span><div className="number">{n}</div><small>{desc}</small></div>)}</div><div className="panel" style={{marginBottom:24}}><div className="panel-head"><div><h2>One journey across four systems</h2><p className="subtext">Department data is translated into a shared application model.</p></div><Workflow color="#4268c7"/></div><div className="network"><div className="network-node"><GraduationCap size={20}/>Citizen portal</div><ArrowRight size={19} color="#8aa0c1"/><div className="network-core"><Link2 size={26} style={{margin:'0 auto 7px'}}/><strong>GovSync core</strong><div style={{fontSize:12,color:'#b8cbed'}}>Consent · Map · Verify</div></div><ArrowRight size={19} color="#8aa0c1"/><div className="stack" style={{gap:8}}>{departments.map(d=><div className="network-node" key={d}>{deptInfo[d].title} API</div>)}</div></div></div><div className="panel"><div className="panel-head"><h2>Department request monitoring</h2><button className="btn small" onClick={()=>void c.refresh()}><RefreshCw size={14}/>Refresh</button></div><Table className="data-table"><TableHeader><TableRow><TableHead>Department</TableHead><TableHead>Requests</TableHead><TableHead>Successful</TableHead><TableHead>Latest result</TableHead><TableHead>Average handler time</TableHead></TableRow></TableHeader><TableBody>{departments.map(d=>{const r=requests.filter((l:any)=>l.department===d);return <TableRow key={d}><TableCell>{deptInfo[d].title}</TableCell><TableCell>{r.length}</TableCell><TableCell>{r.filter((l:any)=>l.outcome==='success').length}</TableCell><TableCell>{r.length?<Badge status={r[0].outcome}/>:<Badge>No requests</Badge>}</TableCell><TableCell>{r.length?Math.round(r.reduce((s:number,l:any)=>s+(l.duration_ms||0),0)/r.length)+' ms':'—'}</TableCell></TableRow>})}</TableBody></Table><div className="panel-body subtext">Timing is measured inside the sample handler, before saving the audit event. This is request history, not live government uptime.</div></div></>;
 if(c.view==='apis')return <div className="panel"><div className="panel-head"><h2>Sample API request console</h2><Badge>SERVER ENDPOINTS</Badge></div><div className="panel-body">{!c.app?<div className="empty"><Code2 size={30}/><h3>Authorize an application first</h3><p>Requests require a saved application and valid consent.</p><button className="btn primary" style={{marginTop:18}} onClick={()=>c.move('apply')}>Open scholarship application</button></div>:<><div className="note" style={{marginBottom:20}}><Info size={17}/><span>Current applicant: <strong>{c.app.name}</strong> · {c.app.citizen_id}. Requests use this application's permissions.</span></div><label className="form-label">Department</label><Select value={dept} onValueChange={v=>setDept(v as Department)}><SelectTrigger className="choice" aria-label="API department"><SelectValue/></SelectTrigger><SelectContent>{departments.map(d=><SelectItem key={d} value={d}>{deptInfo[d].title} API</SelectItem>)}</SelectContent></Select><div className="code" style={{marginTop:16,whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}><span style={{color:'#7cdeb6'}}>GET </span>{`/api/departments/${dept}/${c.app.citizen_id}?applicationId=${c.app.id}${c.outage?'&simulate=unavailable':''}`}</div><div className="actions"><div className="inline"><Checkbox id="api-outage" checked={c.outage} onCheckedChange={v=>c.setOutage(!!v)}/><label htmlFor="api-outage" style={{fontSize:14}}>Simulate 503 unavailable</label></div><button className="btn primary" onClick={send} disabled={c.busy}>{c.busy?<LoaderCircle size={16} className="spin"/>:<Play size={16}/>}Send request</button></div><p className="subtext" style={{marginTop:14}}>Submitted applications cannot fetch records again. Revoked permission returns 403. Start a new application to repeat the full journey.</p>{response&&<><div className="inline" style={{margin:'22px 0 12px'}}><h3>Response</h3><Badge status={status.startsWith('200')?'success':'failed'}>{status}</Badge></div><pre className="code">{JSON.stringify(response,null,2)}</pre></>}</>}</div></div>;
 if(c.view==='mapping')return <div className="panel"><div className="panel-head"><h2>Source-to-profile mappings</h2><Badge>EXPLICIT RULES · NO AI</Badge></div><div className="panel-body"><Tabs value={dept} onValueChange={v=>setDept(v as Department)}><TabsList className="tab-list">{departments.map(d=><TabsTrigger className="tab-trigger" value={d} key={d}>{deptInfo[d].title}</TabsTrigger>)}</TabsList>{departments.map(d=><TabsContent value={d} key={d}><div className="mapping-grid"><div><h3 style={{marginBottom:12}}>Department fields → common fields</h3><pre className="code">{JSON.stringify(mappings[d],null,2)}</pre></div><div><h3 style={{marginBottom:12}}>Transformation</h3><div className="note"><Layers size={19}/><span>{d==='education'?'dob converts from DD/MM/YYYY to YYYY-MM-DD. The name and birth date are compared with Identity before eligibility is decided.':'Named source fields map to the common scholarship profile. The source record stays available for inspection.'}</span></div><p className="subtext" style={{marginTop:15}}>Mappings run on the server. Formatting a value does not establish that it is true.</p></div></div>{c.records[d]?<div className="mapping-grid" style={{marginTop:25}}><div><h3 style={{marginBottom:12}}>Actual sample response</h3><pre className="code">{JSON.stringify(c.records[d].raw,null,2)}</pre></div><div><h3 style={{marginBottom:12}}>Normalized record</h3><pre className="code">{JSON.stringify(c.records[d].normalized,null,2)}</pre></div></div>:<div className="note" style={{marginTop:24}}>Verify an application to inspect its source and normalized records.</div>}</TabsContent>)}</Tabs></div></div>;
 if(c.view==='consent')return <div className="panel"><div className="panel-head"><h2>Application permissions</h2><ShieldCheck color="#3e66c1"/></div><div className="panel-body"><div className="note" style={{marginBottom:22}}><Info size={18}/><span>Revoking consent blocks new department reads and submission. Previously saved records and audit history remain in this demonstration database. New permission requires a new application.</span></div>{c.workspace.applications.length?c.workspace.applications.map((a:any)=><div className="flow-line" key={a.id} style={{flexWrap:'wrap'}}><div className="info-icon"><ShieldCheck size={20}/></div><div style={{flex:1,minWidth:200}}><p>{a.name} · {a.id.slice(0,11)}…</p><small>Purpose: demo scholarship · Four department checks</small><small>Expires: {new Date(a.expires_at).toLocaleString('en-IN')}</small></div><Badge status={a.consent&&a.expires_at>new Date().toISOString()?'success':'blocked'}>{!a.consent?'Revoked':a.expires_at<=new Date().toISOString()?'Expired':'Active'}</Badge><button className="btn small" disabled={c.busy||!a.consent||a.expires_at<=new Date().toISOString()} onClick={()=>c.revoke(a)}>Revoke permission</button></div>):<div className="empty"><ShieldCheck size={30}/><h3>No permissions granted yet</h3><p>Permissions are created when you authorize an application.</p></div>}</div></div>;
 return <div className="panel"><div className="panel-head"><div><h2>Recorded events</h2><p className="subtext">Latest 200 events. Saved logs are not an immutable ledger.</p></div><button className="btn small" onClick={()=>download('Samanvay-audit.json',logs)} disabled={!logs.length}><Download size={15}/>Export JSON</button></div>{logs.length?<Table className="data-table"><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Action / source</TableHead><TableHead>Application</TableHead><TableHead>Result</TableHead><TableHead>Purpose / details</TableHead></TableRow></TableHeader><TableBody>{logs.map((l:any)=><TableRow key={l.id}><TableCell style={{whiteSpace:'nowrap'}}>{new Date(l.created_at).toLocaleTimeString('en-IN')}<div className="subtext">{new Date(l.created_at).toLocaleDateString('en-IN')}</div></TableCell><TableCell><strong>{l.action}</strong><div className="subtext">{l.department?deptInfo[l.department as Department].title:'GovSync core'}</div></TableCell><TableCell title={l.application_id}>{l.application_id?.slice(0,11)}…</TableCell><TableCell><Badge status={l.outcome}/></TableCell><TableCell><div className="audit-detail">{l.details}</div></TableCell></TableRow>)}</TableBody></Table>:<div className="empty"><Activity size={30}/><h3>Your first action starts the trail</h3><p>Authorize an application to see recorded events here.</p></div>}</div>;
}
