'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,ChevronRight,Code2,FileText,GraduationCap,LayoutDashboard,Link2,Layers,ShieldCheck,Activity,BookOpen,LockKeyhole,Info} from 'lucide-react';
import {Sidebar,SidebarProvider,SidebarContent,SidebarFooter,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {departments} from '@/lib/demo';
import Apply from './apply';
import Views from './views';
export const navigation=[{id:'apply',label:'Scholarship application',icon:GraduationCap},{id:'applications',label:'My applications',icon:FileText},{id:'dashboard',label:'Operations overview',icon:LayoutDashboard},{id:'apis',label:'API explorer',icon:Code2},{id:'mapping',label:'Data mappings',icon:Layers},{id:'consent',label:'Consent records',icon:ShieldCheck},{id:'audit',label:'Audit trail',icon:Activity},{id:'guide',label:'Backend guide',icon:BookOpen}];
export const labels:Record<string,string>={draft:'Verification pending',eligible:'Eligible to apply',ineligible:'Not eligible',needs_review:'Needs review',submitted:'Submitted for review'};
export function Badge({status,children}:{status?:string,children?:React.ReactNode}){const tone=['eligible','success','submitted'].includes(status||'')?'green':['ineligible','failed','blocked'].includes(status||'')?'red':['needs_review','review'].includes(status||'')?'orange':'neutral';return <span className={'badge '+tone}>{children||labels[status||'']||status}</span>}
export async function api(path:string,data?:unknown){const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?undefined:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});let j:any;try{j=await r.json()}catch{throw new Error('Unexpected server response. Please retry.')}if(!r.ok)throw Object.assign(new Error(j.error||'Request failed'),{status:r.status});return j;}
export function download(name:string,data:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function Nav({view,setView}:any){const {setOpenMobile}=useSidebar();return <><div className="brand"><span className="brand-symbol"><Link2 size={25}/></span><div>Govsync<small>CONNECTED GOVERNANCE</small></div></div><SidebarContent><div className="nav-label">CITIZEN SERVICES</div><nav className="side-nav">{navigation.map((n,i)=><div key={n.id}>{i===2&&<div className="nav-label" style={{paddingLeft:14,paddingTop:23}}>INTEGRATION WORKSPACE</div>}<button className={'side-item '+(view===n.id?'active':'')} onClick={()=>{setView(n.id);setOpenMobile(false)}} aria-current={view===n.id?'page':undefined}><n.icon size={18}/>{n.label}</button></div>)}</nav></SidebarContent><SidebarFooter className="side-bottom"><div className="inline" style={{marginBottom:8}}><ShieldCheck size={17}/> SIH 2026 · Team Seva-Setu</div><span>Sample data workspace<br/>GovSync interoperability core</span></SidebarFooter></>}
export default function Workspace(){
 const [view,setView]=useState('apply'),[workspace,setWorkspace]=useState<any>({applications:[],audit:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState(false),[busy,setBusy]=useState(false);
 const [citizen,setCitizen]=useState('DEMO-1001'),[scopes,setScopes]=useState<string[]>([]),[app,setApp]=useState<any>(null),[records,setRecords]=useState<Record<string,any>>({}),[checks,setChecks]=useState<Record<string,string>>({}),[stage,setStage]=useState(0),[outage,setOutage]=useState(false),[email,setEmail]=useState('asha@example.test'),[statement,setStatement]=useState('I am applying for this demonstration scholarship to support my undergraduate studies.'),[confirmed,setConfirmed]=useState(false);
 async function refresh(){try{const w=await api('workspace');setWorkspace(w);setAuth(false)}catch(e:any){if(e.status===401)setAuth(true);else setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void refresh()},[]);
 function move(v:string){setView(v);setError('')}
 function reset(){setApp(null);setRecords({});setChecks({});setStage(0);setScopes([]);setConfirmed(false);setError('');setOutage(false);setView('apply')}
 async function openApp(a:any){setBusy(true);setError('');try{const d=await api('applications/'+a.id);setApp(d.application);setCitizen(a.citizen_id);setRecords(Object.fromEntries(d.checks.map((c:any)=>[c.department,{raw:JSON.parse(c.raw),normalized:JSON.parse(c.normalized)}])));setChecks(Object.fromEntries(d.checks.map((c:any)=>[c.department,'success'])));setStage(a.status==='submitted'?3:a.result?2:1);setEmail(a.email||'applicant@example.test');setStatement(a.statement||'I am applying for this demonstration scholarship to support my undergraduate studies.');setConfirmed(false);setOutage(false);setView('apply')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function runChecks(a:any,simulate:boolean){let failed=false;setStage(1);for(const d of departments){setChecks(s=>({...s,[d]:'loading'}));try{const data=await api(`departments/${d}/${a.citizen_id}?applicationId=${encodeURIComponent(a.id)}${simulate&&d==='income'?'&simulate=unavailable':''}`);setRecords(s=>({...s,[d]:data}));setChecks(s=>({...s,[d]:'success'}))}catch(e:any){setChecks(s=>({...s,[d]:'failed'}));setError(e.message);failed=true}}if(!failed){const d=await api(`applications/${a.id}/evaluate`,{});setApp(d.application);setStage(2)}await refresh()}
 async function begin(){setBusy(true);setError('');try{const d=await api('applications',{citizenId:citizen,scopes,accepted:true});setApp(d.application);await runChecks(d.application,outage)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function retry(){setBusy(true);setError('');setOutage(false);try{await runChecks(app,false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const d=await api(`applications/${app.id}/submit`,{email,statement,confirmed});setApp(d.application);setStage(3);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function revoke(a:any){setBusy(true);setError('');try{await api(`applications/${a.id}/revoke`,{});if(app?.id===a.id)setApp({...app,consent:0});await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const ctx={view,workspace,loading,busy,setBusy,auth,citizen,setCitizen,scopes,setScopes,app,setApp,records,setRecords,checks,stage,outage,setOutage,email,setEmail,statement,setStatement,confirmed,setConfirmed,refresh,move,reset,openApp,begin,retry,submit,revoke,setError};
 const heading=navigation.find(n=>n.id===view)!;
 return <SidebarProvider><Sidebar><Nav view={view} setView={move}/></Sidebar><div className="shell"><header className="topbar"><div className="topbar-left"><SidebarTrigger className="mobile-trigger"/><span className="workspace-label muted">Workspace</span><ChevronRight size={14} color="#9ba8bc"/><span style={{fontSize:14,fontWeight:600}}>{heading.label}</span></div><div className="inline"><span className="badge orange">DEMO ENVIRONMENT</span><span className="account-label muted" style={{fontSize:13}}>Team Seva-Setu</span><div className="avatar">SS</div></div></header><main className="workspace"><div className="heading"><div><div className="eyebrow">{view==='apply'?'ONE APPLICATION. FOUR CONNECTED DEPARTMENTS.':'GOVSYNC INTEROPERABILITY CORE'}</div><h1>{view==='apply'?'Your scholarship, simplified.':heading.label}</h1><p>{view==='apply'?'Give permission once. Let connected services do the paperwork.':view==='dashboard'?'Follow the activity generated by your scholarship workflows.':view==='apis'?'Send a real request to a sample department and inspect its response.':view==='mapping'?'See how department records become one consistent profile.':view==='guide'?'Understand the backend and create your own sample APIs.':view==='consent'?'Control information sharing for each application.':view==='audit'?'A saved record of consent, data access and decisions.':'Resume a verification or track a submitted application.'}</p></div>{view!=='apply'&&<button className="btn primary" onClick={reset} disabled={busy}><GraduationCap size={17}/>New application</button>}</div><div className="demo-banner"><Info size={16}/><span>SIH prototype · Fictional citizens, sample APIs and illustrative rules. No live government integration.</span></div>{auth&&<div className="note warn" style={{marginBottom:20}}><LockKeyhole size={18}/><div>Sign in to save and verify demo applications.<br/><a className="btn primary" style={{marginTop:12}} href="/signin-with-chatgpt?return_to=/" target="_top">Sign in to workspace<ArrowRight size={16}/></a></div></div>}{error&&<div role="alert" className="note error" style={{marginBottom:20}}><Info size={18}/><div>{error}<button className="btn small" style={{marginLeft:12}} onClick={()=>{setError('');void refresh()}}>Refresh workspace</button></div></div>}{view==='apply'?<Apply ctx={ctx}/>:<Views ctx={ctx}/>}<footer className="view-footer"><span>Govsync · Interoperability prototype</span><span>SIH 2026 · Sample records only</span></footer></main></div></SidebarProvider>
}
