import {env} from 'cloudflare:workers';
export function database(){if(!env.DB)throw new Error('Database unavailable');return env.DB;}
export class ApiError extends Error{constructor(public status:number,message:string){super(message);}}
export function owner(request:Request){const user=request.headers.get('oai-authenticated-user-id');if(!user)throw new ApiError(401,'Sign in to use the scholarship workspace.');if(request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new ApiError(403,'This request must come from your workspace.');}return user;}
export async function application(id:string,user:string){const row=await database().prepare('SELECT * FROM applications WHERE id = ? AND owner = ?').bind(id,user).first<any>();if(!row)throw new ApiError(404,'Application not found.');return row;}
export function consent(row:any,scope?:string){if(!row.consent||row.expires_at<=new Date().toISOString())throw new ApiError(403,'Consent is revoked or expired. Start a new application with fresh consent.');if(scope&&!JSON.parse(row.scopes).includes(scope))throw new ApiError(403,`Permission for ${scope} has not been granted.`);}
export function event(user:string,appId:string|null,action:string,outcome:string,details:string,dept:string|null=null,duration:number|null=null){return database().prepare('INSERT INTO audit (id,owner,application_id,action,department,outcome,details,duration_ms,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(crypto.randomUUID(),user,appId,action,dept,outcome,details,duration,new Date().toISOString());}
export async function body(request:Request){try{const text=await request.text();if(text.length>12000)throw new Error();const value=JSON.parse(text);if(!value||typeof value!=='object'||Array.isArray(value))throw new Error();return value;}catch{throw new ApiError(400,'A valid JSON request body is required (maximum 12 KB).');}}
export function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}});}
export async function guarded(fn:()=>Promise<Response>){try{return await fn();}catch(e){if(e instanceof ApiError)return reply({error:e.message},e.status);console.error('SevaSetu request failed',e);return reply({error:'The service could not complete this request. Your saved application is retained. Please retry.'},503);}}
